---
- name: For CIFS mounts, ensure the credentials file exists
  ansible.builtin.copy:
    content: |
      domain={{ item.domain }}
      username={{ item.username }}
      password={{ item.password }}
    dest: "{{ item.path }}"
    mode: "0600"
    owner: root
    group: root
  loop: "{{ fstab_cifs_credentials }}"
  when: fstab_cifs_credentials | length > 0

- name: Ensure mountpoints are examined
  when: fstab_mounts | length > 0
  block:
    - name: Ensure mountpoint folder exists
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      loop: "{{ fstab_mounts }}"

    - name: Ensure filesystem are mounted
      ansible.posix.mount: "{{ item }}"
      loop: "{{ fstab_mounts }}"
