---
- name: For CIFS mounts, ensure the credentials file exists
  ansible.builtin.copy:
    content: |
      domain={{ item.domain }}
      username={{ item.username }}
      password={{ item.password }}
    dest: "{{ item.path }}"
    mode: "0600"
    owner: root
    group: root
  loop: "{{ fstab_cifs_credentials }}"
  when: fstab_cifs_credentials | length > 0

- name: Ensure mountpoints are examined
  ansible.builtin.include_tasks: mounts.yml
  when: fstab_mounts | length > 0
  loop: "{{ fstab_mounts }}"
